variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version
  - docker container stop $(docker container ls -aq)
  - docker volume rm memento_web-root -f
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote

build:
  script:
    - docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - memento

