image: docker/compose:latest
-services:
  - docker:dind
variables: 
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  
before_script:
  - docker verison
  - docker-compose version

build:
  stage:
    - build
  tags:
    - memento
  script:
    - docker-compose build --no-cache
 
deploy:
  stage:
    - deploy
  tags:
    - memento
 script:
   - docker-compose up -d
