image: docker:latest
variables: 
  DOCKER_TLS_CERTDIR: "/certs"
services: 
  - docker:dind
  
before_script:
  - docker info

build:
  stage: build
  script: 
    - docker-compose build --no-cache
 
deploy:
 stage: deploy
 script:
  - docker-compose up -d
