image: docker:latest
variables: 
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
services: 
  - docker:dind
  
before_script:
  - docker info

build:
  tags:
    - memento
  stage: build
  script:
    - sudo apt install docker-compose
    - docker-compose build --no-cache
 
deploy:
  tags:
    - memento
  stage: deploy
 script:
   - sudo apt install docker-compose
   - docker-compose up -d
