before_script:
  - who
  - docker version
  - docker-compose version
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote

build:
  script:
    - docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - memento

