image: docker:latest

services: 
  - docker:dind
  
  stages:
    - deploy
    
    step-deploy-production:
      stage: deploy
      only: 
        - master
      tags:
        - production
      script:
        - echo "Setting up memento"
        - sudo docker image prune -f
        - sudo docker-compose build --no-cache
        - sudo docker-compose up -d
    when: manual
