variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version
  - docker system prune -f # remove unused containers, images, etc.
  - docker volume prune -f # remove unused
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote

build:
  script:
    - docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - memento

