version: '3.6'
volumes:
  mongo_data:
  certbot-etc:
  certbot-var:
  web-root:
networks:
  memento:
    driver: bridge
services:
  #memento api
  db:
    image: mongo
    restart: always
    networks:
      - memento
    ports:
      - 2701:2701
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - web-root:/srv/memento/
      - /srv/memento/api
    image: api:memento
    container_name: mementoapi
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - memento
    links:
      - db
    environment:
      - MONGO_HOST=mongo:27017
      - PORT=8000
    ports:
      - '8000:8000'
  #memento db

  #memento client
  client:
    build:
      context: ./memento-ui
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - memento
    volumes:
      - web-root:/srv/memento
      - /srv/memento/ui
    image: client:memento
    container_name: mementoclient
    restart: unless-stopped

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
      - db
      - client
    networks:
      - memento

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - memento
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email sheku.kanneh12@gmail.com --agree-tos --no-eff-email --staging -d memento.sheku-kanneh.com

