version: '3.6'
volumes:
  mongo_data:
  certbot-etc:
  certbot-var:
networks:
  nginx-proxy:
    external: true
    name: nginx_nginx-proxy
  memento:
    name: memento
    driver: bridge
services:
  #memento db
  db:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
    - mongo_data:/data/db
    networks:
      - memento
    ports:
      - 27017:27017
  # memento api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:memento
    container_name: memento_api
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - memento
      - nginx-proxy
    links:
      - db
    environment:
      - VIRTUAL_HOST=memento.sheku-kanneh.com
      - VIRTUAL_PORT=8000
      - MONGO_HOST=mongo:27017
      - PORT=8000
      - AUTH_URI



