version: '3.6'
volumes:
  mongo_data:
  certbot-etc:
  certbot-var:
networks:
  default:
    external: true
    name: nginx-proxy
  memento:
    name: memento
    driver: bridge
services:
  #memento db
  db:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
    - ./data:/data/db
    networks:
      - memento
    ports:
      - 27017:27017
  # memento api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:memento
    container_name: memento_api
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - memento
    links:
      - db
    environment:
      - VIRTUAL_HOST:memento.sheku-kanneh.com
      - VIRTUAL_PORT: 8080
      - MONGO_HOST=mongo:27017
      - PORT=8000
    #ports:
     # - '8000:8000'
  #memento db

  #memento client
#  client:
#    build:
#      context: ./memento-ui
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    networks:
#      - memento
#    volumes:
#      - web-root:/srv/memento/ui/build
#    image: client:memento
#    container_name: mementoclient
#    restart: unless-stopped

  memento_api_nginx:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
      - db
    networks:
      - memento

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - memento
    volumes:
      - certbot-etc:/etc/letsen
    depends_on:
          - memento_api_nginx
    command: certonly --webroot --webroot-path=/var/www/html --email sheku.kanneh12@gmail.com --agree-tos --no-eff-email --staging -d memento.sheku-kanneh.comcrypt
      - certbot-var:/var/lib/letsencrypt

