version: '3.6'
volumes:
  mongo_data:
  certbot-etc:
  certbot-var:
networks:
  default:
    external: true
    name: nginx-proxy
  memento:
    name: memento
    driver: bridge
services:
  #memento db
  db:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
    - ./data:/data/db
    networks:
      - memento
    ports:
      - 27017:27017
  # memento api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:memento
    container_name: memento_api
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - memento
    links:
      - db
    environment:
      - VIRTUAL_HOST=memento.sheku-kanneh.com
      - MONGO_HOST=mongo:27017
      - VIRTUAL_PORT=8000
      - PORT=8000
    #ports:
     # - '8000:8000'
  #memento db

  #memento client
#  client:
#    build:
#      context: ./memento-ui
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    networks:
#      - memento
#    volumes:
#      - web-root:/srv/memento/ui/build
#    image: client:memento
#    container_name: mementoclient
#    restart: unless-stopped


